@extends('layout')
@section('content')
<div class="col-sm-8 mt-3 advice-div p-4" style="margin:0 auto; text-align: justify;">
   <ol>
    <li class="mb-2">Nullam eleifend urna lobortis velit fringilla interdum. Aliquam lorem purus, volutpat eu turpis vitae, luctus fermentum urna. Etiam non mauris elementum, luctus nunc sed, bibendum risus. In et nunc metus. Phasellus mattis mollis erat eget tristique. Phasellus a orci in ante varius volutpat. Vestibulum in sem lacus.</li>
    <li class="mb-2">Ut mi lacus, porta vel tortor nec, mattis lobortis arcu. Pellentesque ut auctor velit, non molestie turpis. Aenean sit amet rhoncus dui, in congue mauris. Nunc ornare erat vel risus bibendum, ut aliquam lacus viverra. Duis blandit odio ante. Donec eget sollicitudin velit, id mollis enim. Suspendisse vitae augue lorem. Nam lacus lacus, tempor id gravida lobortis, consequat vel mi. Donec scelerisque sit amet neque at facilisis.</li>
    <li class="mb-2">In vitae tortor sapien. Integer et mattis massa. Nulla tortor augue, bibendum non sodales nec, euismod imperdiet tellus. Cras luctus orci quis mauris placerat blandit nec ut lacus. In hac habitasse platea dictumst. Cras id dolor dapibus, malesuada quam nec, pulvinar lorem. Vivamus scelerisque velit a neque dictum fermentum. In congue purus consequat sagittis dapibus. Morbi congue bibendum diam et semper. Nulla fringilla nisi porttitor nulla consequat consectetur. Vestibulum vulputate, dolor in condimentum auctor, diam diam varius leo, sit amet porttitor tellus lacus eget eros. Suspendisse dapibus auctor arcu ut semper.</li>
    <li class="mb-2">Pellentesque sed malesuada est, sed sagittis orci. Integer consequat at dolor ac mattis. Nullam suscipit massa porttitor, egestas lorem eu, mattis sapien. Duis consequat auctor nulla, at auctor justo maximus eu. Suspendisse potenti. Etiam et imperdiet nulla. Pellentesque id lorem et ligula venenatis accumsan a quis orci. Etiam ut semper urna.</li>
    <li>Donec cursus nulla at laoreet fermentum. Curabitur ornare nisl at urna faucibus sagittis et sit amet ex. Fusce eu augue id elit placerat fringilla. Aliquam at dui risus. Sed in leo justo. Duis interdum, sem non mollis dictum, ex mi vestibulum enim, a rhoncus odio est eget nisi. Nam blandit, nulla sed sodales vulputate, justo ex viverra elit, at vestibulum orci quam ut massa. Duis accumsan facilisis arcu vitae finibus. Cras aliquam ante metus, vel lacinia tortor volutpat vitae. Ut in commodo nibh, nec malesuada urna. Sed et tortor leo. Mauris lobortis vitae erat a lobortis. Phasellus finibus eleifend velit ac porttitor.</li>
   </ol>
</div>
@endsection
